#version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Ensure this matches the actual path where manage.py is located
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"